# Generated by Django 3.2 on 2021-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresDApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_en_cours', models.IntegerField(default=2021, verbose_name="Année (en septembre) utilisée pour l'application")),
                ('decharges_editables', models.BooleanField(default=True, verbose_name="Les syndicats peuvent-ils accéder à l'édition des décharges ?")),
            ],
        ),
    ]
