# Generated by Django 3.2 on 2021-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresdapplication',
            name='corps_annexe',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
