# Generated by Django 3.2 on 2021-05-12 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_parametresdapplication_corps_annexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresdapplication',
            name='corps_annexe',
            field=models.FileField(null=True, upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ods'])]),
        ),
    ]
