# Generated by Django 3.2 on 2021-04-15 10:05

import decharges.decharge.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('code_corps', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code_corps', message='Doit être constitué de 7 lettres majuscules', regex='^\\d{3}$')], verbose_name='Code corps')),
            ],
        ),
        migrations.CreateModel(
            name='TempsDeDecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2021, verbose_name='Année à laquelle le temps de décharge est attribué')),
                ('temps_de_decharge_etp', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='Temps de décharge en ETP')),
                ('syndicat_beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_de_decharges_par_annee', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat bénéficiaire')),
                ('syndicat_donatrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_de_decharges_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat ayant fait don de temps (si vide, on considère que cela vient de la fédération)')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisationTempsDecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M.', 'M.'), ('MME', 'Mme')], default='MME', max_length=10, verbose_name='Civilité')),
                ('prenom', models.CharField(max_length=255, validators=[decharges.decharge.validators.validate_first_name], verbose_name='Prénom')),
                ('nom', models.CharField(max_length=255, validators=[decharges.decharge.validators.validate_last_name], verbose_name='Nom en MAJUSCULES')),
                ('heures_de_decharges', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='Temps de décharge utilisées en heures')),
                ('heures_d_obligation_de_service', models.IntegerField(default=0, verbose_name="Heures d'obligations de service")),
                ('code_etablissement_rne', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_rne', message='Doit être constitué de 7 chiffres + une lettre majuscule', regex='^\\d{7}[A-Z]$')], verbose_name="Code d'établissement (RNE)")),
                ('annee', models.IntegerField(default=2021, verbose_name='Année à laquelle le temps de décharge est utilisé')),
                ('supprime_a', models.DateTimeField(blank=True, null=True, verbose_name='La date à laquelle cette débarge a été supprimée')),
                ('cree_a', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('modifie_a', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
                ('commentaire_de_mise_a_jour', models.TextField(blank=True, help_text='Décrivez factuellement la modification apportée', null=True, verbose_name='Historique des modifications')),
                ('etp', models.DecimalField(decimal_places=5, default=0, help_text='Ne pas utiliser, présent pour des raisons historiques', max_digits=6, verbose_name='ETP consommé')),
                ('corps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decharge.corps', verbose_name='Corps')),
                ('syndicat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisation_temps_de_decharges_par_annee', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat qui utilise ce temps')),
            ],
            options={
                'unique_together': {('nom', 'prenom', 'annee', 'syndicat')},
            },
        ),
        migrations.CreateModel(
            name='UtilisationCreditDeTempsSyndicalPonctuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demi_journees_de_decharges', models.IntegerField(default=0, verbose_name='Demi-journées de décahrges utilisées')),
                ('annee', models.IntegerField(default=2021, verbose_name='Année à laquelle le temps de décharge est utilisé')),
                ('syndicat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisation_cts_ponctuels_par_annee', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat qui utilise ce temps')),
            ],
            options={
                'unique_together': {('annee', 'syndicat')},
            },
        ),
    ]
