# Generated by Django 3.2 on 2021-04-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisationtempsdecharge',
            name='syndicat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisation_temps_de_decharges_par_annee', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat qui utilise ce temps'),
        ),
        migrations.AddField(
            model_name='utilisationcreditdetempssyndicalponctuel',
            name='syndicat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisation_cts_ponctuels_par_annee', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat qui utilise ce temps'),
        ),
        migrations.AddField(
            model_name='tempsdedecharge',
            name='syndicat_beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_de_decharges_par_annee', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat bénéficiaire'),
        ),
        migrations.AddField(
            model_name='tempsdedecharge',
            name='syndicat_donateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temps_de_decharges_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Syndicat ayant fait don de temps (si vide, on considère que cela vient de la fédération)'),
        ),
        migrations.AlterUniqueTogether(
            name='utilisationtempsdecharge',
            unique_together={('nom', 'prenom', 'annee', 'syndicat')},
        ),
        migrations.AlterUniqueTogether(
            name='utilisationcreditdetempssyndicalponctuel',
            unique_together={('annee', 'syndicat')},
        ),
    ]
