# Generated by Django 3.2 on 2021-04-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decharge', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corps',
            options={'ordering': ['code_corps'], 'verbose_name': 'Corps', 'verbose_name_plural': 'Corps'},
        ),
    ]
