# Generated by Django 3.2 on 2021-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decharge', '0003_alter_corps_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisationtempsdecharge',
            name='etp',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Ne pas utiliser, présent pour des raisons historiques', max_digits=6, verbose_name='ETP consommé'),
        ),
    ]
