# Generated by Django 3.2 on 2021-04-20 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decharge', '0004_alter_utilisationtempsdecharge_etp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilisationtempsdecharge',
            unique_together={('nom', 'prenom', 'annee', 'code_etablissement_rne', 'syndicat')},
        ),
    ]
