# Generated by Django 3.2 on 2021-05-11 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decharge', '0005_alter_utilisationtempsdecharge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisationtempsdecharge',
            name='est_une_decharge_solidaires',
            field=models.BooleanField(default=False, help_text="Cocher cette case uniquement si la décharge vient d'un autre syndicat que SUD éducation", verbose_name='Est une décharge solidaires'),
        ),
        migrations.AlterUniqueTogether(
            name='utilisationtempsdecharge',
            unique_together={('nom', 'prenom', 'annee', 'code_etablissement_rne', 'syndicat', 'est_une_decharge_solidaires')},
        ),
    ]
