# Generated by Django 3.2 on 2021-05-11 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decharge', '0006_auto_20210511_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempsdedecharge',
            unique_together={('annee', 'syndicat_donateur', 'syndicat_beneficiaire')},
        ),
    ]
