# Generated by Django 3.2 on 2021-07-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decharge', '0008_alter_utilisationcreditdetempssyndicalponctuel_demi_journees_de_decharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisationtempsdecharge',
            name='civilite',
            field=models.CharField(choices=[('M.', 'M.'), ('MME', 'MME')], default='MME', max_length=10, verbose_name='Civilité'),
        ),
    ]
