# Generated by Django 3.2 on 2021-04-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academie',
            options={'ordering': ['nom']},
        ),
    ]
