# Generated by Django 3.2 on 2021-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_alter_academie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syndicat',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nom'),
        ),
    ]
